/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chat/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AiCompletionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AiChatMessage"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AiChat: {
            /** Format: uuid */
            threadId: string;
            messages: components["schemas"]["AiChatMessage"][];
        };
        AiChatMessage: {
            /** Format: uuid */
            messageId: string;
            role: components["schemas"]["AiMessageRole"];
            content: string;
            references?: null | components["schemas"]["AiChatReference"][];
        };
        AiChatReference: {
            id: string;
            url: string;
            name: string;
        };
        AiCompletionRequest: {
            chat: components["schemas"]["AiChat"];
            reasoningEffort: components["schemas"]["AiReasoningEffort"];
        };
        /** @enum {unknown} */
        AiMessageRole: "User" | "Assistant";
        /** @enum {unknown} */
        AiReasoningEffort: "None" | "Low" | "Medium";
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
